DROP INDEX IF EXISTS AGGREGATE_SNAPSHOT_AGGREGATE_ID_IDX;
DROP INDEX IF EXISTS AGGREGATE_SNAPSHOT_VERSION_IDX;

DROP TABLE IF EXISTS EVENT_STORE.AGGREGATE_SNAPSHOT;

DROP INDEX IF EXISTS EVENT_TRANSACTION_ID_ID_IDX;
DROP INDEX IF EXISTS EVENT_AGGREGATE_ID_IDX;
DROP INDEX IF EXISTS EVENT_VERSION_IDX;

DROP TABLE IF EXISTS EVENT_STORE.EVENT;

DROP INDEX IF EXISTS AGGREGATE_AGGREGATE_TYPE_IDX;

DROP TABLE IF EXISTS EVENT_STORE.AGGREGATE;
